name: Test CI Stata

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
      tags:
        description: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Stata Action
      id: ci-stata
      uses: ./ # Uses an action in the root directory
      with:
        url: ${{ secrets.URL }}
        version: ${{ secrets.VERSION }}
        serial-number: ${{ secrets.SERIAL_NUMBER }}
        code: ${{ secrets.CODE }}
        authorization: ${{ secrets.AUTHORIZATION }}
        first-name: ${{ secrets.FIRST_NAME }}
        last-name: ${{ secrets.LAST_NAME }}
