name: Test CI Stata

on: push

jobs:
  ci-stata:
    runs-on: ubuntu-16.04
    name: Run Stata do-file
    steps:
      - uses: actions/checkout@v2
      - id: ci-stata
        uses: ledwindra/continuous-integration-stata@v1
