name: Test CI Stata

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
      tags:
        description: 'Manual trigger'
        
jobs:
  ci_stata:
    runs-on: ubuntu-latest
    name: Run Stata do-file
    steps:
    - name: Stata Action
      id: ci-stata
      uses: ledwindra/continuous-integration-stata@v1
      with:
        - ur: ${{ secrets.URL }}
        - old_file: ${{ secrets.OLD_FILE }}
        - version: ${{ secrets.VERSION }}
        - serial-number: ${{ secrets.SERIAL_NUMBER }}
        - code: ${{ secrets.CODE }}
        - authorization: ${{ secrets.AUTHORIZATION }}
        - first-name: ${{ secrets.FIRST_NAME }}
        - last-name: ${{ secrets.LAST_NAME }}
