name: Test CI Stata

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
      tags:
        description: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stata Action
      id: ci-stata
      uses: ledwindra/continuous-integration-stata@v1
      with:
        url: ${{ secrets.URL }}
        old-file: ${{ secrets.OLD_FILE }}
        version: ${{ secrets.VERSION }}
        serial-number: ${{ secrets.SERIAL_NUMBER }}
        code: ${{ secrets.CODE }}
        authorization: ${{ secrets.AUTHORIZATION }}
        first-name: ${{ secrets.FIRST_NAME }}
        last-name: ${{ secrets.LAST_NAME }}
        repository-url: ${{ secrets.REPOSITORY_URL }}
        repository-dir: ${{ secrets.REPOSITORY_DIR }}
        
    - name: Set-up git and make a commit
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
        REPOSITORY: ${{ secrets.REPOSITORY }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        git config --local user.email $EMAIL
        git config --local user.name $USERNAME
        git remote set-url origin ${{ secrets.REPOSITORY_URL }}
        git status
        # mv regression-table* latex-table/
        # git status
        # git add data/* latex-table/*
        # git commit --allow-empty -m "Updated data and regression table"
        # git pull --rebase origin main
        # git push -u origin main
