name: Test CI Stata

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
      tags:
        description: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Stata Action
      id: ci-stata
      uses: ledwindra/continuous-integration-stata@v1
      with:
        url: ${{ secrets.URL }}
        old-file: ${{ secrets.OLD_FILE }}
        version: ${{ secrets.VERSION }}
        serial-number: ${{ secrets.SERIAL_NUMBER }}
        code: ${{ secrets.CODE }}
        authorization: ${{ secrets.AUTHORIZATION }}
        first-name: ${{ secrets.FIRST_NAME }}
        last-name: ${{ secrets.LAST_NAME }}
        repository-url: ${{ secrets.REPOSITORY_URL }}
        repository-dir: ${{ secrets.REPOSITORY_DIR }}
        
    - name: Convert LaTeX table to PDF
      run: |
        pwd
        ls -la
        cd /github/home/continuous-integration-stata
        pwd
        sudo apt-get install texlive-latex-base
        mkdir -p latex-table
        # pdflatex regression-table.tex

#     - name: Convert LaTeX to PDF
#       uses: xu-cheng/latex-action@v2
#       with:
#         root_file: /home/runner/work/continuous-integration-stata/continuous-integration-stata/latex-table/regression-table.tex
        
#     - name: Set-up git and make a commit
#       env:
#         ACCESS_TOKEN: ${{ secrets.TOKEN }}
#         EMAIL: ${{ secrets.EMAIL }}
#         REPOSITORY: ${{ secrets.REPOSITORY_DIR }}
#         USERNAME: ${{ secrets.USERNAME }}
#       run: |
#         ls -la
#         ls -la data/
#         ls -la latex-table
#         git config --local user.email $EMAIL
#         git config --local user.name $USERNAME
#         git remote set-url origin https://${USERNAME}:${ACCESS_TOKEN}@github.com/${USERNAME}/${REPOSITORY}.git
#         git status
#         mv regression-table* latex-table/
#         git add data/* latex-table/*
#         git commit --allow-empty -m "Updated data and regression table"
#         git pull --rebase origin main
#         git push -u origin main
