name: Test CI Stata

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stata Action
      id: ci-stata
      uses:  EBoisseauSierra/continuous-integration-stata@main_ebosi
      with:
        stata-licence: ${{ secrets.STATA_LICENCE }}
        stata-edition: ${{ secrets.STATA_EDITION }}
